# WARNING!
# Use this file only for example purposes.
# We're exposing here sensitive ports and services.

services:
  tenancy:
    image: ghcr.io/turnly/tenancy:latest
    ports:
      - 6000:6000
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./context:/app/context
    env_file: ../.env

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: tenancy
